### ISSUE TITLE
Which OS?

### ISSUE THREAD

**Issue by lenusch** [UltimateByte/plesk_mail_autoconfig#1]
Hi, which OS does this Support? 
Can you take care of Debian aswell?

**Comment by UltimateByte** [comment]
Hi,

It is tested for CentOS only for now, our prod at HaiSoft runs CentOS. 
I don't have a Debian Plesk install handy, but if you can provide some details about your install, I think the adaptation will be quite easy. 

I assume the difference will just be httpd being renamed apache2, and then I can just make a conditional check to adjust paths that are already in a variable. The rest is Plesk specific and should be common to every distro. (Of course Windows is and will remain unsupported by me).

I would just need to know your apache2 directories info (`ll` outputs from your apache dirs might help), and especially the location where additional config files are loaded from (if you don't know, have a look at apache2's main config file, it's usually something like `include /path/to/files/*.conf`).

**Comment by lenusch** [comment]
Hi,

thanks, my mate just said that for Plesk Cloudlinux its same.
(in future we want to use Cloudlinux for more security.)

at the Moment, i have following apache2.conf from Plesk:
(See attachment)

And the Settings (SERVER, PORTS, and so on) i have to set in the config.xml files?

We use PLesk 17.5.x on Debian 8.9

httpd is apache2 in Debian.

That would be awesome to get this customized.
When i pull this into our GIT, where to i have to adjust settings to meet Server Settings?
Or are the Setting managable over PLesk GUI? I dont think so.. uhm.

Kindly please advice :-) 


[apache2.conf.zip](https://github.com/UltimateByte/plesk_mail_autoconfig/files/1289665/apache2.conf.zip)

**Comment by UltimateByte** [comment]
Thanks,

I made some adjustments for Debian, however I cannot test them since my Debian machine doesn't run Plesk. But I tested the concept of adding alias config files in conf-enabled recently (here https://github.com/UltimateByte/transmission-deployer/blob/master/transmission-deployer#L536-L548 ) and restarting apache, and it worked perfectly fine, so I'm pretty confident it will work.
Apache commands made here are not dangerous at all, in the worst case it will just add a useless config file.

You can review the changes here: https://github.com/UltimateByte/plesk_mail_autoconfig/commit/1594e27e7ec335f4a1a54f8e02ae5cb7e2ec51cf#diff-0349fc30e589c9eb27b82c1d6dee6f8a

If Cloudlinux uses httpd name for apache with support for conf.d dir, it is then the same as CentOS and should work just fine.

We deployed it on 17.5 as well, tested on a good bunch of production servers with many many domains.
If conditions said in the readme are met, then you should be fine. 

As for editing the config, I believe this won't be required since we use standard secured ports. The only fancy thing is we are allowing port 2525 on top of port 25 for cases where port 25 is blocked by the provider or firewall. If needed, you can edit autodiscover.xml (Outlook), config-v1.1.xml (Thunderbird), iphone.mobileconfig (iPhone) and iphone.xml (iPhone config generation page, especially if you're not French :p ).

Also, if you fork this, don't forget to change these info to yourys:

```
# Git repo, useful if you want to fork it
gituser="UltimateByte"
gitrepo="plesk_mail_autoconfig"
gitbranch="master"
```

Don't hesitate to report any error (or lack of error :p) for your Debian install.

**Comment by lenusch** [comment]
Thank you!!, i hope i will be able to test this later!!
Moreover i found some git where someone reports Apple Mail to function right: 
https://github.com/Tiliq/autodiscover.xml

Maybe you can include that, to have Apple Mail support :-) 👍  We have noticed past years, lot of customers use standard Mac Mail Programm, therefor its interesting to have also mac Mail :)

**Comment by UltimateByte** [comment]
Thanks for your attention. Actually, their method is the same as ours. Go to domain.tld/ios, will do the same as what they propose. I knew the config file was working for iOS, not for Apple Mail, we need to test that. :)

**Comment by lenusch** [comment]
I will install that on Test Plesk (hopefully today) and then i will test mac OS Mail? If theres a chance that this will work. Fortunately i am a Mac user :-D

**Comment by UltimateByte** [comment]
Oh yeah, you're right, I noticed that with the __MACOSX dir inside your .zip file, but I forgot about it already. :p 
Well, awaiting for your feedback, especially on how to used the generated config file on a Mac. :)

**Comment by lenusch** [comment]
Yes. Just tried to install and got following Error: 
`Mail Autoconfig - [ ERROR ] No apache conf.d in /etc/httpd or conf-enabled in /etc/apache2 were found`

Please see Screenshot for which Folderas are within etc/apache2/
![bildschirmfoto 2017-09-09 um 18 13 53](https://user-images.githubusercontent.com/27028016/30241803-d1d14d6a-958a-11e7-9fca-8fc762dcc549.jpg)


WAIT, just see that my test Server is the only Server which hasn't got this Folder right .... :D .. Seems i habe brooken something with my tests last month, uhm

**Comment by lenusch** [comment]
Solution (maybe I crashed the symbolic Link to new Folder.) 
Here it sais: https://serverfault.com/a/777254 that the folder moved to another Folder. 
Can we some how take care of this in your script? "if conf.d not writable, choose conf-available" or something :-) 

but i still get same Error. Check Screenshot please, you need the path to apache2.conf? thats in /etc/apache2/

**Comment by lenusch** [comment]
Okay, its not working. 
`2017-09-09_18:51:53 - Mail Autoconfig - [ INFO ] Detecting if Apache is named apache2 or httpd
2017-09-09_18:51:54 - Mail Autoconfig - [ ERROR ] No apache conf.d in /etc/httpd or conf-enabled in /etc/apache2 were found`

but this folder does exist, as you can see in Screenshot :/

**Comment by UltimateByte** [comment]
Oh yeah, I see my mistake into the code, fixed. ;)
Fix was pretty easy though.
https://github.com/UltimateByte/plesk_mail_autoconfig/commit/9479192844d3d5287206b216085715b2ec50c312

**Comment by lenusch** [comment]
Yes, i already looked at this part of code of course :P didn't know what the "!" was doing. 
Question: Could you kindly translate iphone.xml into english? The only france sentence i can is "je mappelle Lenusch, etoi?" ..
Kindly looking forward to hear from you ;) MERCI

**Comment by UltimateByte** [comment]
So, does it work as intended now ?
I shall add a way to add multiple languages for iOS I think. Damn Apple with their crappy system :o))
I'll see when i got some time, it's saturday night now :p

**Comment by lenusch** [comment]
Well, thunderbird works. 

Outlook for Mac (no)
Mac Mail (nothing happens)
Iphone 7s Mail (nothing happens) 
does the Iphone will open the IOS site by default? 
or do we have to say customers "Hey you need to open https://hostname.com/ios/iphone.xml!" ... 
? If not, then = on Iphone nothing happened, it opened more fields which i had to fill in :-/

**Comment by UltimateByte** [comment]
Apple crap don't have any actual kind of real autoconfig.
You need to visit any domain /ios, and it will point you to the configurator, and download a config file. We tested with iphones already, and it works.
If you could try on your mac i'd be grateful.
For outlook to work, you need to have an HTTPS (Let's Encrypt) certificate on your domain's website.

**Comment by lenusch** [comment]
https on customer domain, or on Hostname? 
Hostname has SSL of course, a payed one :-) 

Some good News: YES Apple Mail over Link, Profil download and install works like a charm! 
Thank you. Thats very good. at least even if few extra steps compared to Thunderbird, it avoids mistakes which customers do ALWAYS. :-) The Profil Manager showed Email succesfull and i had to close and just check apple Mail and there it was, new Email address.

**Comment by lenusch** [comment]
(Outlook 2011 for MacOS it seems always to ask for Settings, as soon as i click into Password field, it opens whole Setting Page)

**Comment by lenusch** [comment]
- I had one Problem, while installing: Hostname was incorrect. The Script pulls Hostname from Server not Plesk? So i changed Debian Hostname to right Hostname, then everything was good :-)

**Comment by UltimateByte** [comment]
HTTPS on customer domain for outlook, like i said, domain.tld, not hostname.tld. Is this requirement met?
Also, requirements say hostname must be valid :p

**Comment by lenusch** [comment]
no it wasn't but it worked with newest Outlook Mac and Outlook on Surface anyways.
But Outlook Mac 2011 will not work, even with Customer Domain SSL :-) 

But i am nearly having everything turned out for good. Many thanks!!!

**Comment by lenusch** [comment]
uhm, i deleted all, and then reinstalled and now it sais: 

[ Warning ] Thunderbird http://hostname/mail/config-v1.1.xml does not seem to be accessible

But files exist on Server. What am i missing? 

`2017-09-09_22:57:15 - Mail Autoconfig - [ ... ] Populating Thunderbird autoconfig file
sed: -e expression #1, char 21: unknown option to `s'`

**Comment by lenusch** [comment]
I can reach IOS Files but not mail/config-v1.1.xml and so on... 
CNAME is setup correctly.
+ DNS is external. Internal DNS is not used.

**Comment by UltimateByte** [comment]
Allright. So the last thing would be to have an Apple config page in English right?
I could make a prompt for language, or a setting to put into the config file. 
Problem here is I would like to keep the default to French

**Comment by UltimateByte** [comment]
Here is a translation.
https://github.com/UltimateByte/plesk_mail_autoconfig/blob/master/iphone_en.xml

You can add it manually for now.

**Comment by lenusch** [comment]
Thank you. Still can't open mail/config-v1.1.xml 
(befor i thought it was working because i had this folder setup manually. I reverted my changes from last month) now i can't reach mail/config-v1.1.xml

**Comment by UltimateByte** [comment]
What's the error when you visit the url?

**Comment by lenusch** [comment]
404 Not found :/

**Comment by UltimateByte** [comment]
Can you please provide the following commands outputs?

```bash
ls -al /var/www/vhosts/default/htdocs/
ls -al /var/www/vhosts/default/htdocs/mail
cat  /var/www/vhosts/default/htdocs/mail/.htaccess
cat /etc/apache2/conf-enabled/autodiscover.conf
```

**Comment by lenusch** [comment]
```
# ls -al /var/www/vhosts/default/htdocs/
total 136
drwxr-xr-x 5 root root   4096 Sep  9 20:51 .
drwxr-xr-x 5 root root   4096 Feb  2  2017 ..
drwxr-xr-x 2 root root   4096 Jun  7 01:12 css
-rw-r--r-- 1 root root 113459 Oct 26  2016 favicon.ico
drwxr-xr-x 2 root root   4096 Jun  7 01:12 img
-rw-r--r-- 1 root root   3703 Jun  5 19:44 index.html
drwxr-xr-x 2 root root   4096 Sep 10 07:50 mail
```

```
# ls -al /var/www/vhosts/default/htdocs/mail
total 68
drwxr-xr-x 2 root root  4096 Sep 10 07:50 .
drwxr-xr-x 5 root root  4096 Sep  9 20:51 ..
-rw-r--r-- 1 root root   191 Sep 10 07:50 .htaccess
lrwxrwxrwx 1 root root    52 Sep  9 20:51 Autodiscover.xml -> /var/www/vhosts/default/htdocs/mail/autodiscover.xml
-rw-r--r-- 1 root root  1430 Sep 10 07:50 autodiscover.xml
-rw-r--r-- 1 root root  2602 Sep 10 07:49 config-v1.1.xml
-rw-r--r-- 1 root root  2482 Sep 10 07:50 iphone.mobileconfig
-rw-r--r-- 1 root root  1857 Sep 10 07:50 iphone.xml
-rw-r--r-- 1 root root 24762 Sep  9 21:01 logo.png
-rw-r--r-- 1 root root 11279 Sep 10 07:50 logo.svg
```

**the rights of the "Autodiscover" File, are they right? Seems a bit to much lrwxrwxrwx :-/**

```
# cat  /var/www/vhosts/default/htdocs/mail/.htaccess
AddHandler php-script .php .xml
RewriteEngine on
RewriteCond %{REQUEST_URI} !iphone.xml
RewriteCond %{REQUEST_URI} !logo.svg
RewriteCond %{REQUEST_URI} ios
RewriteRule .* /ios/iphone.xml [R]
```

```
# cat /etc/apache2/conf-enabled/autodiscover.conf
Alias /autodiscover "/var/www/vhosts/default/htdocs/mail"
Alias /Autodiscover "/var/www/vhosts/default/htdocs/mail"
Alias /ios "/var/www/vhosts/default/htdocs/mail"
```

is it right to have this conf file inserted to "conf-anabled" as this folder seems to contain only "@" Files. 
Last time i tested to get some CONF working, i used the "conf-available" folder. 
any rewrite i did in a File in that Folder was working. 

Dont know?! ..

**Comment by UltimateByte** [comment]
1) No worries about rights on Autodiscover.xml, it's just because it's a symlink to autodiscover.xml.

2) Yes it is. 
Having stuff in conf-available just forces you to symlink them into conf-enable by using "a2enmod". When apache starts, it loads everything in mods-enabled, so I'm just avoiding a useless step by doing it this way.

Actually, everything is OK with your config. 
You should not be able to reach http://customerdomain.tld/mail/config-v1.1.xml but rather
http://autoconfig.customerdomain.tld/mail/config-v1.1.xml
As said into the readme, https://github.com/UltimateByte/plesk_mail_autoconfig#requirements > Do you have autoconfig.customerdomain.tld as an A type DNS redirection to your host IP?

Explanation: Since autoconfig.yourdomain.tld should point to your host, but not exist as a subdomain, if you or thunderbird try to access it, it will display the default plesk directory : "htdocs". In the end, by visiting http://autoconfig.customerdomain.tld/mail/config-v1.1.xml , thunderbird will reach /var/www/vhosts/default/htdocs/mail/config-v1.1.xml

**Comment by lenusch** [comment]
i had it with CNAME, but changed it to A record directly to IP. 
Yes, thats what i thought, seems everything ok. 
I HAD the autoconfig as a subdomain within Plesk but deleted it long time before. Maybe theres something which is messing around? 

"You should not be able to reach http://customerdomain.tld/mail/config-v1.1.xml but rather
http://autoconfig.customerdomain.tld/mail/config-v1.1.xml"

Both is not working, after change to A Record. :// 

But, to test URL and DNS I tried to open "http://autoconfig.customerdomain.tld/ios/" and this works!! :///

**Comment by UltimateByte** [comment]
Does autoconfig.customerdomain.tld points to your host IP?
(A type or CNAME, doesn't matter as long as it points to it)

When you got to Plesk settings and click "IP addresses" and click your main IP, is the default site set to "None" as it should?

That's the two only conditions that could not be met and explain that it doesn't work for you.

**Comment by lenusch** [comment]
Yes and NONe is set in Settings of course. 
i deleted old vhosts Folder and recreated config Files vhosts... 
Wont work EXCEPT: 
if i call https://customerdomain.tld/mail/config-v1.1.xml (SSL) and skip "no zertifikat" IT WORKS. 
if i open http://customerdomain.tld/mail/config-v1.1.xml it works not. 

so on Port 80 it doesn't work. 
on Port 443 (after skipping message) it works. 

I really don't understand that ...

**Comment by UltimateByte** [comment]
If you have any /mail alias vhost on, make sure to remove it and restart apache.
If you created a domain autoconfig.customerdomain.tld, make sure to remove it. The point is, it has to be non-existant in order to be redirected to the default Plesk's directory.

**Comment by UltimateByte** [comment]
Your issue is most likely that you need to undo properly whatever you did before using the script.

**Comment by lenusch** [comment]
Yes, 
i installed new Plesk and now after restarting apache2 few times and changing IP to NONE (again) it seems working. 

Really creepy, have no clue what the Problem was. I undo my changes from few month ago... 
Maybe i really have missed something.

Sorry and thank you for your great script!!

**Comment by lenusch** [comment]
Any Plans to make that Apple Profil signed with valid Signature? 
Because Customer gets a RED alert "unsigned". 
I see some examples for that here (scroll down please) 
https://dokuwiki.nausch.org/doku.php/centos:mail_c6:autoconfig_3

**Comment by UltimateByte** [comment]
We're OK with the unsigned mail config signature for now. Given the context with which you access the URL, customers put enough trust in it to validate the config file.
On top of that, it seems almost impossible to add this signature using a script. But feel free to pull-request if you got something to propose.

**Comment by lenusch** [comment]
Okay, one more Question: i saw Script installing CNAMES for every Domain within Plesk internal DNS.
We don't use internal DNS. Will this work anyway? Or do we have to create for each single Domain on Plesk a Subdomain "autoconfig" ?

**Comment by UltimateByte** [comment]
This is answered two times into the readme. 

> Your DNS zones shall preferably be managed into Plesk, otherwise, for Thunderbird autoconfig to work, you just need to add the following CNAME to your domain names' DNS zones: autoconfig > [hostname].tld.

> Adds a CNAME to all your domains for Thunderbird autoconfig : autoconfig > [hostname].tld. (If your DNS zone is not managed into Plesk, make sure to add this entry into it.)

**Comment by lenusch** [comment]
Yes, thank you.
You can correct Readme by MacOS Mail (per Config) and we also tested with "Windows Mail" and it was success :-)

**Comment by lenusch** [comment]
Maybe you could optionally put some Value into installation Script to ignore creating internal DNS Records, as this is now going through 300 Domains atm and creating useless Data :P 
10 minutes ago since i have started Script :P 
This will never be relevant because i wont have internal DNS enabled. 

runinternalCNAMEconfig="1" (choose 1/0)

**Comment by lenusch** [comment]
And its the second time i get following Error but everything works PERFECT :P 

"0curl: (35) error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
2017-09-13_18:04:24 - Mail Autoconfig - [ Warning ] Outlook https://......"

**Comment by UltimateByte** [comment]
Documentation has evolved enough to cover this, I hope. New issues can be opened if needed, this one is solved.
