### ISSUE TITLE
Problems with iPad

### ISSUE THREAD

**Issue by lenusch** [UltimateByte/plesk_mail_autoconfig#10]
Hi, are there any known Problems with iPad? 
Some Customers can't install and or if they install, whole iCloud Connections are destroid and some other things will not work anymore. Thus after installing Profile.... 

Any Suggestions or know Problems? 
Limitations?

**Comment by MegaS0ra** [comment]
Hi, 
No known problem currently.

What is the problem/error for those who can't install the profile?

As iCloud connections and Profiles are two different things, I'm not sure how it can be related.

I've not been able to reproduce the issue on my side.
Please provide more details if possible.

Thanks

**Comment by lenusch** [comment]
Uhm, this Tool has no Certificate right? so if I install a Profil, theres always "Not Signed" .... 
Well the Customer reported again, that there where 3 hours trying to solve all Problems with a Customers Ipad and so on.... There where some Apple Supporter which mentioned that our "unsecure" profile may caused this Problem. After removing all Profile from us, the icloud could gain Connection again. 
Really strange, as i can't confirm such Problem on any Device. 
But I am worried about that....

**Comment by lenusch** [comment]
PERFECT !!!! I have reproduced this Issue, as i randomly have exactly same Ipad. 
So a second Customer with an Ipad Mini iOS 9.3.5 has reported, he can't connect to Server. 

I opened same Account, Profil with MY IPAD with Open Console in Macbook and got following Error: 

" CFNetwork SSLHandshake failed (-9806)"

And after that, Ipad shows in middle of profil installation following Error "
LogOther <t: 0x15d95540> ERROR: MFMessageErrorDomain / Generic - IMAP server "mail.hostname.com" is not responding. Check your network connection and that you have entered the correct information under "Server for incoming e-mails"."

So here i can't get any further. Mail wont work. 
What can i do? 
I think, the mobileconfig Files needs some adjustments, as refered here: 

https://stackoverflow.com/questions/30720813/cfnetwork-sslhandshake-failed-ios-9

**Comment by MegaS0ra** [comment]
The post on stackoverflow seems to refer to TLS version on the server.
So first, can you confirm:
- Does the page where your download the profile from is HTTPS secured ?
- Does your server uses TLS 1.2 for HTTPS access ?
(You can test both here : https://www.ssllabs.com/ssltest/)

- Did you configured the profile with SSL/TLS settings for IMAP/SMTP ?
- If so, does your mail server presents a certificate as the same name "mail.hostname.com" upon connection ?

**Comment by MegaS0ra** [comment]
Closed due to inactivity
