### ISSUE TITLE
Disable service for one domain

### ISSUE THREAD

**Issue by dna75** [UltimateByte/plesk_mail_autoconfig#11]
Where do I change the code;
Alias "/autodiscover" "/var/www/vhosts/DOMAIN.TLD/httpdocs/autodiscover"
Alias "/Autodiscover" "/var/www/vhosts/DOMAIN.TLD/httpdocs/autodiscover"

I want to exclude a domain who is using office365 and not my mail-server / service.

I'm using centos7

_Originally posted by @dna75 in https://github.com/HaiSoftSARL/plesk_mail_autoconfig/issues/5#issuecomment-448151842_

**Comment by MegaS0ra** [comment]
In Plesk, in the "Apache & nginx Settings" of the domain in "Additional directives for HTTPS".

Screenshots:
https://cloud.haisoft.net/index.php/s/QSbBdzPGa92w5zf/preview
https://cloud.haisoft.net/index.php/s/b4afRgcE3yjZsNY/preview

**Comment by dna75** [comment]
Thanks! Didn't realize it should be done within Plesk. 
Just tested it, and it works.
