### ISSUE TITLE
Question please

### ISSUE THREAD

**Issue by lenusch** [UltimateByte/plesk_mail_autoconfig#13]
Hi, 

whats an example Output of this one? 
```xml
<string>
    com.apple.mdm.HOSTNAME.%first_uuid%.COMPANYLOWERCASENAME</string>
```
That would help me alot.

**Comment by UltimateByte** [comment]
Hello,
An example would be : 

`com.apple.mdm.myhostname.domain.tld.%first_uuid%.domaincompany</string>`

For faster support, please note that the project moved here : https://gitlab.haisoft.net/pub/Plesk_MailAutoconfig

Best
