### ISSUE TITLE
Profil gets overriden from new Profil

### ISSUE THREAD

**Issue by lenusch** [UltimateByte/plesk_mail_autoconfig#2]
Hi, 

today we installed on a Iphone two Profiles. 
But the First one gets always overriden from second one. 
What am i missing or is this a bug or something which can't be handeled? 
That would be really bad :-) :-( 

Please kindly advice.

**Comment by UltimateByte** [comment]
Mhh, I'm not an iPhone owner/user myself, and we followed documentation we found about iOS stuff.
Maybe it has something to do with the string here
https://github.com/UltimateByte/plesk_mail_autoconfig/blob/master/iphone.mobileconfig#L49
and here
https://github.com/UltimateByte/plesk_mail_autoconfig/blob/master/iphone.mobileconfig#L73
that would maybe need to be different in order to prevent overlap?

**Comment by lenusch** [comment]
Docs: 
PayloadUUID | String | A globally unique identifier for the profile. The actual content is unimportant, but it must be globally unique. In macOS, you can use uuidgen to generate reasonable UUIDs.
-- | -- | --


https://developer.apple.com/library/content/featuredarticles/iPhoneConfigurationProfileRef/Introduction/Introduction.html#//apple_ref/doc/uid/TP40010206-CH1-SW7

This is probably the Problem!?

**Comment by lenusch** [comment]
Maybe some Template here - could you merge that? 
https://github.com/mritd/strongswan/blob/master/generate-mobileconfig.sh

or this: 
https://github.com/hunk/get-UDID

or this: 
https://ryanbritton.com/2016/07/creating-a-mobileconfig-file-to-capture-ios-udid-information/

but i am not able to set this up. :-S

**Comment by UltimateByte** [comment]
Problem is I don't speak PHP. I tested the above bash script but I don't get what's it's actually doing.
I need to talk about this to my coworkers who know more PHP than me, but expect it to be quite long since we got other priorities at the moment. We kind of consider the iOS thing like a bonus.

**Comment by lenusch** [comment]
uhm okay, could you make a paid request out of it? 
As our Customers reporting this behaviour

**Comment by UltimateByte** [comment]
Well, we're a hosting company, so we don't code for other people. We are mainly developing this based on our needs and are kindly sharing it with the world. But be sure I'll try to see what we can do about this as soon as I can.

Awaiting for this, please, don't forget that your customers can also use the manual way on their Apple devices if this doesn't work for them.

**Comment by lenusch** [comment]
Thank you, i will await your reply.

**Comment by UltimateByte** [comment]
Well, we examined this many times and didn't come up with a solution.
I'll keep it open, until hopefully one day we come with a fix for this.
In the meantime, I added an entry here about that
https://github.com/UltimateByte/plesk_mail_autoconfig/wiki/Limitations

**Comment by UltimateByte** [comment]
Good news @lenusch, @MegaS0ra is on his way to bring a solution to this.

**Comment by MegaS0ra** [comment]
I think I have solved it, at least it works with the new config I just updated on github.
If it is not too late, please keep us updated :)
Thanks
