### ISSUE TITLE
Thunderbird autodiscover URL not found

### ISSUE THREAD

**Issue by campsjos** [UltimateByte/plesk_mail_autoconfig#4]
After configuring and running it, all the DNS records and files are created as expected. 
I can see the `/var/www/vhosts/default/htdocs/mail` dir and the XML files and I can also browse successfully to `https://domain.tls/autodiscover/autodiscover.xml`, `https://domain.tls/Autodiscover/Autodiscover.xml` but I get a 404 error on `https://autoconfig.domain.tls/mail/config-v1.1.xml` or `https://domain.tls/mail/config-v1.1.xml` so Thunderbird isn't getting the autoconfig data.

**Comment by campsjos** [comment]
Looking at the apache logs, when add an account to Thunderbird it makes a request to `https://domain.tls/.well-known/autoconfig/mail/config-v1.1.xml?emailaddress=username@domain.tls`.
After adding `Alias /.well-known/autoconfig/mail "/var/www/vhosts/default/htdocs/mail"` to `/etc/httpd/conf.d/autodiscover.conf` autodiscover works as expected.

**Comment by UltimateByte** [comment]
I see no logical reason for your apache server to default redirect in .well-known, unless you have special .htaccess rules or a weird default URL for your Plesk.

**Comment by campsjos** [comment]
My default URL is just my company domain and it hasn't any uncommon .htaccess rule. The server hostname is a subdomain of another domain with no sites in it.
I think it's not about my server configuration, but Thunderbird just making this request:

> Given the email address "fred@example.com", Thunderbird first checks <http://autoconfig.example.com/mail/config-v1.1.xml?emailaddress=fred@example.com> and then <http://example.com/.well-known/autoconfig/mail/config-v1.1.xml>.

[Thunderbird docs](https://developer.mozilla.org/en-US/docs/Mozilla/Thunderbird/Autoconfiguration)

**Comment by UltimateByte** [comment]
> My default URL is just my company domain and it hasn't any uncommon .htaccess rule.

Well, here might be your issue. You should disable the default URL for this to work, since this entire script relies on this condition.
Example (masked off the ip):
![example](http://image.noelshack.com/fichiers/2018/03/1/1516039217-def-ip.png)

**Comment by campsjos** [comment]
And this explicitly in the requirements section of this repo...
>Your Plesk default domain must be set to "None" (default).

Excuse me for no reading the instructions properly. 
I'll try it tomorrow. I'm closing this issue, I'll open it again in case there's anything to add.
Thanks!

**Comment by UltimateByte** [comment]
That's OK no worries ;)
