### ISSUE TITLE
Override for specific Customers

### ISSUE THREAD

**Issue by lenusch** [UltimateByte/plesk_mail_autoconfig#5]
HI, 
is it possible to override / Disable this for specific Customers?

**Comment by UltimateByte** [comment]
Hi,

It is, as said in the FAQ : https://github.com/UltimateByte/plesk_mail_autoconfig/wiki/FAQ#what-if-i-want-to-disable-autoconfig-for-one-domain-only

Regards

**Comment by lenusch** [comment]
HI @UltimateByte , 
that would be nice, to override default Settings for a Specific Customer. 
I tried this, but it wont work, uhm. 
See screenshot. 

File: /etc/apache2/conf-enabled/autodiscover.conf
```
#ALL CUSTOMERS
Alias /autodiscover "/var/www/vhosts/default/htdocs/mail"
Alias /Autodiscover "/var/www/vhosts/default/htdocs/mail"
Alias /ios "/var/www/vhosts/default/htdocs/mail"

#EXLCUDE
Alias /autodiscover "/var/www/vhosts/customerdomain.de/httpdocs"
Alias /Autodiscover "/var/www/vhosts/customerdomain.de/httpdocs"
```

**Comment by UltimateByte** [comment]
That doesn't work like that. If you want to edit a specific domain, the most obvious way is to edit the domain's vhost, to override the /a(A)utodiscover path.

**Comment by UltimateByte** [comment]
BTW, this is achieved in `Apache & nginx Settings` of the domain in `Additional directives for HTTPS`.

**Comment by lenusch** [comment]
uhm - my bad. Sorry - missunderstood :-D

**Comment by UltimateByte** [comment]
No problem :)
So were you able to get it sorted?

**Comment by lenusch** [comment]
Yes, awesome, thank you! I have tested successfully and will apply tomorrow. 
As for no i had commented whole Alias out because of an Urgent Request.

**Comment by UltimateByte** [comment]
Allright, good to know :)

**Comment by dna75** [comment]
I can't get my head around where to change / add the code:
Alias "/autodiscover" "/var/www/vhosts/DOMAIN.TLD/httpdocs/autodiscover"
Alias "/Autodiscover" "/var/www/vhosts/DOMAIN.TLD/httpdocs/autodiscover"

I want to exclude a domain who is using office365 and not my mail server / service.

I'm using centos7

**Comment by MegaS0ra** [comment]
In Plesk, in the "Apache & nginx Settings" of the domain in "Additional directives for HTTPS".

Screenshots:
https://cloud.haisoft.net/index.php/s/QSbBdzPGa92w5zf/preview
https://cloud.haisoft.net/index.php/s/b4afRgcE3yjZsNY/preview
