### ISSUE TITLE
Mail Autoconfig - [ Warning ] Apple http://domain/apple does not seem to be accessible

### ISSUE THREAD

**Issue by dna75** [UltimateByte/plesk_mail_autoconfig#7]
When I take a look at the test results everything is alright except I get the warning;
Mail Autoconfig - [ Warning ] Apple http://{domain}/apple does not seem to be accessible

I tried to manually create this folder but it doesn't help.

**Comment by MegaS0ra** [comment]
On our side, we often get this warning, but accessing the URL manually works. It fails sometimes because of DNS propagation or because the check is done just after apache was restarted.

Do you confirm you can't access this URL manually, and does the folder exists ?
Does the autoconfig/autodiscover links work for you ?

**Comment by MegaS0ra** [comment]
I have fixed something.

This check would always fail, since on the previous commits, we changed all files from "ios" and "iphone" to "apple". The check would look for
`form method="post" action="iphone.xml"`
==> fixed by replacing it with
`form method="post" action="apple.xml"`

It may help with your issue.

https://github.com/HaiSoftSARL/plesk_mail_autoconfig/commit/712d756935f1622e6a4d8624399db007e86c3ea0

**Comment by UltimateByte** [comment]
I think we can consider this resolved. Feel free to re-open the issue if needed.

Thanks for pointing this out.

**Comment by UltimateByte** [comment]
Just saw your post here: https://github.com/HaiSoftSARL/plesk_mail_autoconfig/commit/712d756935f1622e6a4d8624399db007e86c3ea0#commitcomment-29163259

If your file is empty, it means there is an issue somewhere. Full output of the script execution could be interesting.

**Comment by dna75** [comment]
I changed th line in autoconfig.sh file to 'apple'.
Still when I run the script the Apple.xml file remains empty.

The redirect is working when I go to domain.nl/apple -> the rewrite to domain.nl/apple/apple.xml works. The file is has also been chmodded.

Output;
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2452  100  2452    0     0  16657      0 --:--:-- --:--:-- --:--:-- 16680
2018-05-30_01:07:40 - Mail Autoconfig - [ OK ] Thunderbird http://autoconfig.domain.nl/mail/config-v1.1.xml is accessible

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1134    0  1134    0     0   3440      0 --:--:-- --:--:-- --:--:--  3436
2018-05-30_01:07:41 - Mail Autoconfig - [ OK ] Outlook https://domain.nl/autodiscover/autodiscover.xml is accessible

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1134  100  1134    0     0   4058      0 --:--:-- --:--:-- --:--:--  4064
2018-05-30_01:07:42 - Mail Autoconfig - [ OK ] Outlook https://domain.nl/Autodiscover/Autodiscover.xml is accessible

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   178  100   178    0     0  14415      0 --:--:-- --:--:-- --:--:-- 14833
100   239  100   239    0     0    942      0 --:--:-- --:--:-- --:--:--   942
100   224  100   224    0     0    866      0 --:--:-- --:--:-- --:--:--   866
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
2018-05-30_01:07:43 - Mail Autoconfig - [ Warning ] Apple http://domain.nl/apple does not seem to be accessible
2018-05-30_01:07:43 - Mail Autoconfig - [ OK ] Done

**Comment by UltimateByte** [comment]
What about the part here:
"[INFO] Creating Apple web page"

Here:
"[ ... ] Populating Apple config files"

And here:
"[ INFO ] Writing Apple config files"

Any other output next to these?

**Comment by dna75** [comment]
Part 1:
2018-05-30_09:04:34 - Mail Autoconfig - [ ... ] Populating Apple config files

2018-05-30_09:04:35 - Mail Autoconfig - [ INFO ] Writing htaccess file

2018-05-30_09:04:35 - Mail Autoconfig - [ INFO ] Writing autodiscover Apache configuration file

2018-05-30_09:04:36 - Mail Autoconfig - [ INFO ] Restarting Apache
'httpd' is not a command

---

Part 2
2018-05-30_09:04:32 - Mail Autoconfig - [ INFO ] Writing Apple config files

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2808  100  2808    0     0   8590      0 --:--:-- --:--:-- --:--:--  8613
2018-05-30_09:04:33 - Mail Autoconfig - [ ... ] Downloading logo.png logo for Apple web page
--2018-05-30 09:04:34--  https://raw.githubusercontent.com/HaiSoftSARL/plesk_mail_autoconfig/master/logo.png
Herleiden van raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.36.133
Verbinding maken met raw.githubusercontent.com (raw.githubusercontent.com)|151.101.36.133|:443... verbonden.
HTTP-verzoek is verzonden; wachten op antwoord... 200 OK
Lengte: 24762 (24K) [image/png]
Wordt opgeslagen als: ‘/var/www/vhosts/default/htdocs/mail/logo.png’

**Comment by UltimateByte** [comment]
"'httpd' is not a command" is weird. What's your distro already?
Rest of the output is irrelevant. I would need to see the output from the apple file downloading and editing.

By any means, are you trying to run the script with "sh" rather than with "bash"? That could explain this weird behaviour.

What happens when you run these commands manually?
```
curl https://raw.githubusercontent.com/HaiSoftSARL/plesk_mail_autoconfig/master/apple_en.xml > /var/www/vhosts/default/htdocs/mail/apple.xml

service httpd restart
service apache2 restart
```

**Comment by dna75** [comment]
I'm running CentOS Linux release 7.5.1804

When I'm running your curl command;
[root@srv4 ~]# curl https://raw.githubusercontent.com/HaiSoftSARL/plesk_mail_autoconfig/master/apple_en.xml > /var/www/vhosts/default/htdocs/mail/apple.xml
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2254  100  2254    0     0   6357      0 --:--:-- --:--:-- --:--:--  6367

--

When I restart httpd I have to use systemctl restart httpd
Can't execute ther apache2 restart command (Failed to restart apache2.service: Unit not found.)

Edit: I'm running the script with Bash

**Comment by UltimateByte** [comment]
So after this command, is your file written or not?

**Comment by dna75** [comment]
No it's still empty, every config file contains the config (including the applemobile) except for the apple.xml

**Comment by UltimateByte** [comment]
So there is an issue either with your curl or with the `>` redirection.
If you just input this, do you see the file content ?

`curl https://raw.githubusercontent.com/HaiSoftSARL/plesk_mail_autoconfig/master/apple_en.xml`

If not, to diagnose furthermore, you can use curl -v instead of curl.

`curl -v https://raw.githubusercontent.com/HaiSoftSARL/plesk_mail_autoconfig/master/apple_en.xml`

**Comment by dna75** [comment]
When I run the curl command I do see the file content.
Going crazy.. removed everything.. and installed again.. still the same issue.

**Comment by MegaS0ra** [comment]
So you can try to download the file with wget:
`wget https://raw.githubusercontent.com/HaiSoftSARL/plesk_mail_autoconfig/master/apple_en.xml`
and then move it to the right folder ?
`mv apple_en.xml /var/www/vhosts/default/htdocs/mail/apple.xml`

--

I will try with a fresh install of CentOS 7.5.1804, and the latest Plesk version (17.8.11)

Also, what's your Plesk version ?

**Comment by MegaS0ra** [comment]
One more thought:
Did you change the setting «applewebpagelanguage» to another language than "en" or "fr" ?
Our repo only contains two preconfigured files : apple_en.xml and apple_fr.xml

**Comment by dna75** [comment]
That's it! I mindlessly changed the language everytime to NL.... 
Thank you so much for you 'one more thought! And thanks to the others for their patience!

It's working perfect now.

**Comment by MegaS0ra** [comment]
Fix/workaround for this
fabc401
