### ISSUE TITLE
Folder Mapping wrong 

### ISSUE THREAD

**Issue by lenusch** [UltimateByte/plesk_mail_autoconfig#8]
Hi! 
Is there something wrong with folder Mapping and or can we control mapping with this auto config?

I often get some Feedback, that mapping was Not ok.

**Comment by UltimateByte** [comment]
We changed /ios to /apple recently, because it now works with Apple Mail desktop software.
Other than that, we have no "mapping" issues. But everything is configurable if you check the script, we made sure all directories are in variables to allow easy editing.

**Comment by lenusch** [comment]
hi,
thx. Oh /apple instead of ios? 
that means, i wont need to download profiles for apple mail desktop, because apple mail will pull right settings?

**Comment by UltimateByte** [comment]
No, that means profile work for apple mail desktops with multiple profiles, just as on mobile phones now, thanks to @MegaS0ra 's work. :)

**Comment by UltimateByte** [comment]
I'll close this issue unless there is more details pointing to a real issue.

Regards
