### ISSUE TITLE
Prefix path Horde

### ISSUE THREAD

**Issue by dna75** [UltimateByte/plesk_mail_autoconfig#9]
My settings require to insert a Prefix path in the mail client (inbox) so the folder structure will be downloaded. Is it possible to auto configure that also?

**Comment by MegaS0ra** [comment]
Do you mean the IMAP prefix?
For Apple's autoconfig, it seems to be a setting according to this thread :
https://forums.developer.apple.com/thread/7203
`<key>IncomingMailServerIMAPPathPrefix</key>
<string>EXAMPLE</string>`

For Outlook & Thunderbird, it does not seem to be possible, at least I found nothing about it, except this thread about the same problem :
https://talk.plesk.com/threads/avoid-root-folder-path-inbox.343112/#post-828203

**Comment by dna75** [comment]
Yes I meant the IMAP prefix. What a shame that I can't remove it for Courier. 
I could switch to Dovecot but existing clients would have to reconfigure.
It would have been great to get it working because users now still have to manually configure the prefix (except voor Apple users).

**Comment by dna75** [comment]
Maybe this will help others;
Since the auto configure for the INBOX prefix won't work cross-platform I have changed to dovecot and changed the dovecot.conf file.

I changed;
# Default private namespace setup compatible with Courier-IMAP.
namespace inbox {
separator = /
prefix =
inbox = yes
}
namespace compat {
separator = .
prefix = INBOX.
inbox = no
hidden = yes
list = no
alias_for =
}

Existing users wil be able to keep working with the INBOX prefix and you can auto configure new accounts without a prefix.
